apiVersion: v2
# upstream version
appVersion: APP_VERSION_PLACEHOLDER
# giantswarm app version
version: CHART_VERSION_PLACEHOLDER
name: rancher-fleet
description: Fleet Controller - GitOps at Scale
home: https://github.com/giantswarm/rancher-fleet
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  io.giantswarm.application.audience: "giantswarm"
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: "rocket"
  io.giantswarm.application.upstream-chart-url: "https://github.com/rancher/fleet/tree/main/charts/fleet"
  io.giantswarm.application.upstream-chart-version: "APP_VERSION_PLACEHOLDER"
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
dependencies:
  - name: rancher-fleet-crds
    version: CRD_VERSION_PLACEHOLDER
sources:
  - https://github.com/rancher/fleet
